# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 074ebf8aaaeec5c933a529c79eceb2add45fe1a5ffb3d2ceb78ed52a3721a0e819721bcf4d43fd83575baf9e8c4d49ad00b14fb466bd11bf9ef3b7dc2ea7b68d

test:
  secret_key_base: 869af5ae402f3b681f96e2ef408f58a77c184764678105ddc925125dafd6e2374a18d328419198633438703f5ca645a7f280be0d020f9a7376b04dd4df50c51e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
